name: Merge Schedule
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  merge_schedule_for_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: gr2m/merge-schedule-action@v1
        with:
          merge_method: rebase
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
